<a href="https://colab.research.google.com/github/RamaB47/Projet-Isigny-Ste-Mere/blob/main/fichier_global_fusionn%C3%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = "Donnees_lait.xlsx"
info_lait = pd.read_excel(df)
info_lait.head()

,Figure 1 : collecte de lait et part des signes de qualité,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Retour sommaire
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Lait de vache,NaN,NaN,NaN,Lait de chèvre,NaN,Lait de brebis,NaN,NaN,NaN
2,NaN,Quantité,Évolution sur un an,Part du lait bio,Part du lait AOP/IGP,Quantité,Évolution sur un an,Quantité,Évolution sur un an,NaN,NaN
3,NaN,1 000 l,%,%,%,1 000 l,%,1 000 l,%,NaN,NaN
4,Janvier 2020,2115961,1.3,4.3,16.8,25743,5.1,37693,6.9,NaN,NaN

In [3]:
Col =["Unnamed: 2", "Unnamed: 3","Unnamed: 4","Unnamed: 5","Unnamed: 6", "Unnamed: 7", "Unnamed: 8", "Unnamed: 9", "Retour sommaire"]

In [4]:
info_lait.drop(Col, axis= 1, inplace=True)

In [5]:
info_lait.head()

  Figure 1 : collecte de lait et part des signes de qualité     Unnamed: 1
0                                                NaN                   NaN
1                                                NaN         Lait de vache
2                                                NaN              Quantité
3                                                NaN               1 000 l
4                                       Janvier 2020               2115961

In [6]:
df_rename = info_lait.rename(columns = {
    "Figure 1 : collecte de lait et part des signes de qualité" : "Date",
    "Unnamed: 1": "Qté 1000L"
    })

In [7]:
print(df_rename)

                                                 Date      Qté 1000L
0                                                 NaN            NaN
1                                                 NaN  Lait de vache
2                                                 NaN       Quantité
3                                                 NaN        1 000 l
4                                        Janvier 2020        2115961
..                                                ...            ...
64                                       Janvier 2025        1963404
65                                       Février 2025        1819754
66                                          Mars 2025        2064221
67                                                NaN            NaN
68  Source : Agreste - Enquête mensuelle laitière ...            NaN

[69 rows x 2 columns]

In [8]:
df_rename.to_csv("info_lait.csv")

In [9]:
date_mois = {
    "Janvier": "01",
    "Février": "02",
    "Mars": "03",
    "Avril":"04",
    "Mai": "05",
    "Juin": "06",
    "Juillet": "07",
    "Août": "08",
    "Septembre": "09",
    "Octobre": "10",
    "Novembre": "11",
    "Décembre": "12"
}

In [10]:
print(df_rename['Date'].unique())

[nan 'Janvier 2020' 'Février 2020' 'Mars 2020' 'Avril 2020' 'Mai 2020'
 'Juin 2020' 'Juillet 2020' 'Août 2020' 'Septembre 2020' 'Octobre 2020'
 'Novembre 2020' 'Décembre 2020' 'Janvier 2021' 'Février 2021' 'Mars 2021'
 'Avril 2021' 'Mai 2021' 'Juin 2021' 'Juillet 2021' 'Août 2021'
 'Septembre 2021' 'Octobre 2021' 'Novembre 2021' 'Décembre 2021'
 'Janvier 2022' 'Février 2022' 'Mars 2022' 'Avril 2022' 'Mai 2022'
 'Juin 2022' 'Juillet 2022' 'Août 2022' 'Septembre 2022' 'Octobre 2022'
 'Novembre 2022' 'Décembre 2022' 'Janvier 2023' 'Février 2023' 'Mars 2023'
 'Avril 2023' 'Mai 2023' 'Juin 2023' 'Juillet 2023' 'Août 2023'
 'Septembre 2023' 'Octobre 2023' 'Novembre 2023' 'Décembre 2023'
 'Janvier 2024' 'Février 2024' 'Mars 2024' 'Avril 2024' 'Mai 2024'
 'Juin 2024' 'Juillet 2024' 'Août 2024' 'Septembre 2024' 'Octobre 2024'
 'Novembre 2024' 'Décembre 2024' 'Janvier 2025' 'Février 2025' 'Mars 2025'
 'Source : Agreste - Enquête mensuelle laitière FranceAgriMer / SSP']

In [11]:
# 1. On sépare le mois et l'année en deux colonnes temporaires
df_rename['Date'] = df_rename['Date'].str.strip()

In [12]:
df_split = df_rename['Date'].str.split(r'\s+', n=1, expand=True)

In [13]:
df_rename['Nom_Mois'] = df_split[0]
df_rename['Annee'] = df_split[1]

In [14]:
print(df_rename)

                                                 Date      Qté 1000L Nom_Mois  \
0                                                 NaN            NaN      NaN
1                                                 NaN  Lait de vache      NaN
2                                                 NaN       Quantité      NaN
3                                                 NaN        1 000 l      NaN
4                                        Janvier 2020        2115961  Janvier
..                                                ...            ...      ...
64                                       Janvier 2025        1963404  Janvier
65                                       Février 2025        1819754  Février
66                                          Mars 2025        2064221     Mars
67                                                NaN            NaN      NaN
68  Source : Agreste - Enquête mensuelle laitière ...            NaN   Source

                                                Annee
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                2020
..                                                ...
64                                               2025
65                                               2025
66                                               2025
67                                                NaN
68  : Agreste - Enquête mensuelle laitière FranceA...

[69 rows x 4 columns]

In [15]:
print(df_rename.dtypes)

Date         object
Qté 1000L    object
Nom_Mois     object
Annee        object
dtype: object

In [16]:
ligne_drop = [0,1,2,3]

In [17]:
df_rename.drop(axis=0, index = ligne_drop, inplace=True)

In [18]:
print(df_rename)

                                                 Date Qté 1000L Nom_Mois  \
4                                        Janvier 2020   2115961  Janvier
5                                        Février 2020   2008677  Février
6                                           Mars 2020   2164352     Mars
7                                          Avril 2020   2117406    Avril
8                                            Mai 2020   2109591      Mai
..                                                ...       ...      ...
64                                       Janvier 2025   1963404  Janvier
65                                       Février 2025   1819754  Février
66                                          Mars 2025   2064221     Mars
67                                                NaN       NaN      NaN
68  Source : Agreste - Enquête mensuelle laitière ...       NaN   Source

                                                Annee
4                                                2020
5                                                2020
6                                                2020
7                                                2020
8                                                2020
..                                                ...
64                                               2025
65                                               2025
66                                               2025
67                                                NaN
68  : Agreste - Enquête mensuelle laitière FranceA...

[65 rows x 4 columns]

In [19]:
Month = {"Janvier": "01",
      "Février": "02",
      "Mars": "03",
      "Avril":"04",
      "Mai": "05",
      "Juin": "06",
      "Juillet": "07",
      "Août": "08",
      "Septembre": "09",
      "Octobre": "10",
      "Novembre": "11",
      "Décembre": "12"}

In [20]:
df_rename["MM"] = df_rename['Nom_Mois'].map(Month)

In [21]:
print(df_rename)

                                                 Date Qté 1000L Nom_Mois  \
4                                        Janvier 2020   2115961  Janvier
5                                        Février 2020   2008677  Février
6                                           Mars 2020   2164352     Mars
7                                          Avril 2020   2117406    Avril
8                                            Mai 2020   2109591      Mai
..                                                ...       ...      ...
64                                       Janvier 2025   1963404  Janvier
65                                       Février 2025   1819754  Février
66                                          Mars 2025   2064221     Mars
67                                                NaN       NaN      NaN
68  Source : Agreste - Enquête mensuelle laitière ...       NaN   Source

                                                Annee   MM
4                                                2020   01
5                                                2020   02
6                                                2020   03
7                                                2020   04
8                                                2020   05
..                                                ...  ...
64                                               2025   01
65                                               2025   02
66                                               2025   03
67                                                NaN  NaN
68  : Agreste - Enquête mensuelle laitière FranceA...  NaN

[65 rows x 5 columns]

In [22]:
df_rename["AAAAMM"]= df_rename["Annee"] + df_rename["MM"]

In [23]:
print(df_rename)

                                                 Date Qté 1000L Nom_Mois  \
4                                        Janvier 2020   2115961  Janvier
5                                        Février 2020   2008677  Février
6                                           Mars 2020   2164352     Mars
7                                          Avril 2020   2117406    Avril
8                                            Mai 2020   2109591      Mai
..                                                ...       ...      ...
64                                       Janvier 2025   1963404  Janvier
65                                       Février 2025   1819754  Février
66                                          Mars 2025   2064221     Mars
67                                                NaN       NaN      NaN
68  Source : Agreste - Enquête mensuelle laitière ...       NaN   Source

                                                Annee   MM  AAAAMM
4                                                2020   01  202001
5                                                2020   02  202002
6                                                2020   03  202003
7                                                2020   04  202004
8                                                2020   05  202005
..                                                ...  ...     ...
64                                               2025   01  202501
65                                               2025   02  202502
66                                               2025   03  202503
67                                                NaN  NaN     NaN
68  : Agreste - Enquête mensuelle laitière FranceA...  NaN     NaN

[65 rows x 6 columns]

In [24]:
Col1 = ["Date","Nom_Mois", "Annee", "MM"]

In [25]:
df_rename.drop(Col1, axis= 1, inplace=True)

In [26]:
print(df_rename)

   Qté 1000L  AAAAMM
4    2115961  202001
5    2008677  202002
6    2164352  202003
7    2117406  202004
8    2109591  202005
..       ...     ...
64   1963404  202501
65   1819754  202502
66   2064221  202503
67       NaN     NaN
68       NaN     NaN

[65 rows x 2 columns]

In [27]:
from datetime import datetime

In [28]:
df_rename['AAAAMM'] = pd.to_datetime(df_rename['AAAAMM'], format='%Y%m')

In [29]:
print(df_rename)

   Qté 1000L     AAAAMM
4    2115961 2020-01-01
5    2008677 2020-02-01
6    2164352 2020-03-01
7    2117406 2020-04-01
8    2109591 2020-05-01
..       ...        ...
64   1963404 2025-01-01
65   1819754 2025-02-01
66   2064221 2025-03-01
67       NaN        NaT
68       NaN        NaT

[65 rows x 2 columns]

In [30]:
# On retransforme la vraie date en texte "YYYYMM"
df_rename['AAAAMM'] = df_rename['AAAAMM'].dt.strftime('%Y%m')

In [31]:
print(df_rename)

   Qté 1000L  AAAAMM
4    2115961  202001
5    2008677  202002
6    2164352  202003
7    2117406  202004
8    2109591  202005
..       ...     ...
64   1963404  202501
65   1819754  202502
66   2064221  202503
67       NaN     NaN
68       NaN     NaN

[65 rows x 2 columns]

In [32]:
df_rename.to_csv("info_lait_final.csv")

In [33]:
dataset1 ="fichier_meteo_final.csv"
dataset2 = "info_lait_final.csv"

In [34]:
df_m = pd.read_csv(dataset1)
df_l = pd.read_csv(dataset2)

In [35]:
print(df_m)

     AAAAMM      RR  NBRR     TX     TN     TM
0    195802   64.20  18.0    NaN    NaN    NaN
1    195803   55.90  31.0    NaN    NaN    NaN
2    195804   25.90  30.0    NaN    NaN    NaN
3    195805   52.20  31.0    NaN    NaN    NaN
4    195806  100.90  30.0    NaN    NaN    NaN
..      ...     ...   ...    ...    ...    ...
817  202603   25.00  31.0  13.40   6.15   9.75
818  202604    5.10  30.0  16.00   8.35  12.20
819  202605   38.10  31.0  19.20  11.00  15.10
820  202606   40.75  30.0  22.55  13.45  18.05
821  202607    0.00   1.0  23.70  13.25  18.50

[822 rows x 6 columns]

In [36]:
df_final = pd.merge(df_m, df_l, on=['AAAAMM'], how='left')
print(df_final)

     AAAAMM      RR  NBRR     TX     TN     TM  Unnamed: 0  Qté 1000L
0    195802   64.20  18.0    NaN    NaN    NaN         NaN        NaN
1    195803   55.90  31.0    NaN    NaN    NaN         NaN        NaN
2    195804   25.90  30.0    NaN    NaN    NaN         NaN        NaN
3    195805   52.20  31.0    NaN    NaN    NaN         NaN        NaN
4    195806  100.90  30.0    NaN    NaN    NaN         NaN        NaN
..      ...     ...   ...    ...    ...    ...         ...        ...
817  202603   25.00  31.0  13.40   6.15   9.75         NaN        NaN
818  202604    5.10  30.0  16.00   8.35  12.20         NaN        NaN
819  202605   38.10  31.0  19.20  11.00  15.10         NaN        NaN
820  202606   40.75  30.0  22.55  13.45  18.05         NaN        NaN
821  202607    0.00   1.0  23.70  13.25  18.50         NaN        NaN

[822 rows x 8 columns]

In [37]:
df_final.tail(30)

     AAAAMM      RR  NBRR     TX     TN     TM  Unnamed: 0  Qté 1000L
792  202402  120.55  29.0  12.25   7.40   9.80        53.0  1929745.0
793  202403   57.65  31.0  13.20   5.70   9.45        54.0  2092191.0
794  202404   46.60  30.0  15.30   7.40  11.35        55.0  2049047.0
795  202405   68.65  31.0  17.70  10.10  13.90        56.0  2093404.0
796  202406   17.70  30.0  19.40  10.75  15.05        57.0  1934348.0
797  202407   43.25  31.0  21.90  13.45  17.65        58.0  1900241.0
798  202408   39.60  31.0  23.35  13.85  18.65        59.0  1810170.0
799  202409  109.80  30.0  18.80  12.35  15.60        60.0  1752744.0
800  202410   70.80  31.0  17.45   9.95  13.70        61.0  1828747.0
801  202411   83.45  30.0  12.50   7.55  10.00        62.0  1792633.0
802  202412   66.25  31.0  10.05   5.75   7.90        63.0  1902042.0
803  202501  176.45  31.0   8.50   2.10   5.30        64.0  1963404.0
804  202502   44.35  28.0   9.70   3.30   6.55        65.0  1819754.0
805  202503   40.85  31.0  12.70   5.25   8.95        66.0  2064221.0
806  202504   22.00  30.0  14.95   7.80  11.40         NaN        NaN
807  202505   31.25  31.0  17.45  10.80  14.10         NaN        NaN
808  202506   59.35  30.0  22.00  13.10  17.55         NaN        NaN
809  202507   99.50  31.0  22.50  14.35  18.45         NaN        NaN
810  202508   30.85  31.0  22.70  14.25  18.50         NaN        NaN
811  202509   93.20  30.0  20.25  11.95  16.10         NaN        NaN
812  202510   85.85  31.0  16.65  10.30  13.50         NaN        NaN
813  202511   72.35  30.0  13.90   7.80  10.90         NaN        NaN
814  202512   48.55  31.0  10.80   5.35   8.05         NaN        NaN
815  202601   93.80  31.0  10.20   4.05   7.15         NaN        NaN
816  202602  112.60  28.0  12.55   7.05   9.80         NaN        NaN
817  202603   25.00  31.0  13.40   6.15   9.75         NaN        NaN
818  202604    5.10  30.0  16.00   8.35  12.20         NaN        NaN
819  202605   38.10  31.0  19.20  11.00  15.10         NaN        NaN
820  202606   40.75  30.0  22.55  13.45  18.05         NaN        NaN
821  202607    0.00   1.0  23.70  13.25  18.50         NaN        NaN

In [38]:
df_final.to_csv("fichier global finalisé.csv")