<a href="https://colab.research.google.com/github/RamaB47/Projet-Isigny-Ste-Mere/blob/main/fichier_global_fusionn%C3%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = "Donnees_lait.xlsx"
info_lait = pd.read_excel(df)
info_lait.head()

,Figure 1 : collecte de lait et part des signes de qualité,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Retour sommaire
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Lait de vache,NaN,NaN,NaN,Lait de chèvre,NaN,Lait de brebis,NaN,NaN,NaN
2,NaN,Quantité,Évolution sur un an,Part du lait bio,Part du lait AOP/IGP,Quantité,Évolution sur un an,Quantité,Évolution sur un an,NaN,NaN
3,NaN,1 000 l,%,%,%,1 000 l,%,1 000 l,%,NaN,NaN
4,Janvier 2020,2115961,1.3,4.3,16.8,25743,5.1,37693,6.9,NaN,NaN

In [3]:
Col =["Unnamed: 2", "Unnamed: 3","Unnamed: 4","Unnamed: 5","Unnamed: 6", "Unnamed: 7", "Unnamed: 8", "Unnamed: 9", "Retour sommaire"]

In [4]:
info_lait.drop(Col, axis= 1, inplace=True)

In [5]:
info_lait.head()

  Figure 1 : collecte de lait et part des signes de qualité     Unnamed: 1
0                                                NaN                   NaN
1                                                NaN         Lait de vache
2                                                NaN              Quantité
3                                                NaN               1 000 l
4                                       Janvier 2020               2115961

In [6]:
df_rename = info_lait.rename(columns = {
    "Figure 1 : collecte de lait et part des signes de qualité" : "Date",
    "Unnamed: 1": "Qté 1000L"
    })

In [7]:
print(df_rename)

                                                 Date      Qté 1000L
0                                                 NaN            NaN
1                                                 NaN  Lait de vache
2                                                 NaN       Quantité
3                                                 NaN        1 000 l
4                                        Janvier 2020        2115961
..                                                ...            ...
64                                       Janvier 2025        1963404
65                                       Février 2025        1819754
66                                          Mars 2025        2064221
67                                                NaN            NaN
68  Source : Agreste - Enquête mensuelle laitière ...            NaN

[69 rows x 2 columns]

In [8]:
df_rename.to_csv("info_lait.csv")

In [9]:
date_mois = {
    "Janvier": "01",
    "Février": "02",
    "Mars": "03",
    "Avril":"04",
    "Mai": "05",
    "Juin": "06",
    "Juillet": "07",
    "Août": "08",
    "Septembre": "09",
    "Octobre": "10",
    "Novembre": "11",
    "Décembre": "12"
}

In [10]:
print(df_rename['Date'].unique())

[nan 'Janvier 2020' 'Février 2020' 'Mars 2020' 'Avril 2020' 'Mai 2020'
 'Juin 2020' 'Juillet 2020' 'Août 2020' 'Septembre 2020' 'Octobre 2020'
 'Novembre 2020' 'Décembre 2020' 'Janvier 2021' 'Février 2021' 'Mars 2021'
 'Avril 2021' 'Mai 2021' 'Juin 2021' 'Juillet 2021' 'Août 2021'
 'Septembre 2021' 'Octobre 2021' 'Novembre 2021' 'Décembre 2021'
 'Janvier 2022' 'Février 2022' 'Mars 2022' 'Avril 2022' 'Mai 2022'
 'Juin 2022' 'Juillet 2022' 'Août 2022' 'Septembre 2022' 'Octobre 2022'
 'Novembre 2022' 'Décembre 2022' 'Janvier 2023' 'Février 2023' 'Mars 2023'
 'Avril 2023' 'Mai 2023' 'Juin 2023' 'Juillet 2023' 'Août 2023'
 'Septembre 2023' 'Octobre 2023' 'Novembre 2023' 'Décembre 2023'
 'Janvier 2024' 'Février 2024' 'Mars 2024' 'Avril 2024' 'Mai 2024'
 'Juin 2024' 'Juillet 2024' 'Août 2024' 'Septembre 2024' 'Octobre 2024'
 'Novembre 2024' 'Décembre 2024' 'Janvier 2025' 'Février 2025' 'Mars 2025'
 'Source : Agreste - Enquête mensuelle laitière FranceAgriMer / SSP']

In [11]:
# 1. On sépare le mois et l'année en deux colonnes temporaires
df_rename['Date'] = df_rename['Date'].str.strip()

In [12]:
df_split = df_rename['Date'].str.split(r'\s+', n=1, expand=True)

In [13]:
df_rename['Nom_Mois'] = df_split[0]
df_rename['Annee'] = df_split[1]

In [14]:
print(df_rename)

                                                 Date      Qté 1000L Nom_Mois  \
0                                                 NaN            NaN      NaN
1                                                 NaN  Lait de vache      NaN
2                                                 NaN       Quantité      NaN
3                                                 NaN        1 000 l      NaN
4                                        Janvier 2020        2115961  Janvier
..                                                ...            ...      ...
64                                       Janvier 2025        1963404  Janvier
65                                       Février 2025        1819754  Février
66                                          Mars 2025        2064221     Mars
67                                                NaN            NaN      NaN
68  Source : Agreste - Enquête mensuelle laitière ...            NaN   Source

                                                Annee
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                2020
..                                                ...
64                                               2025
65                                               2025
66                                               2025
67                                                NaN
68  : Agreste - Enquête mensuelle laitière FranceA...

[69 rows x 4 columns]

In [15]:
print(df_rename.dtypes)

Date         object
Qté 1000L    object
Nom_Mois     object
Annee        object
dtype: object

In [16]:
ligne_drop = [0,1,2,3]

In [17]:
df_rename.drop(axis=0, index = ligne_drop, inplace=True)

In [18]:
print(df_rename)

                                                 Date Qté 1000L Nom_Mois  \
4                                        Janvier 2020   2115961  Janvier
5                                        Février 2020   2008677  Février
6                                           Mars 2020   2164352     Mars
7                                          Avril 2020   2117406    Avril
8                                            Mai 2020   2109591      Mai
..                                                ...       ...      ...
64                                       Janvier 2025   1963404  Janvier
65                                       Février 2025   1819754  Février
66                                          Mars 2025   2064221     Mars
67                                                NaN       NaN      NaN
68  Source : Agreste - Enquête mensuelle laitière ...       NaN   Source

                                                Annee
4                                                2020
5                                                2020
6                                                2020
7                                                2020
8                                                2020
..                                                ...
64                                               2025
65                                               2025
66                                               2025
67                                                NaN
68  : Agreste - Enquête mensuelle laitière FranceA...

[65 rows x 4 columns]

In [22]:
Month = {"Janvier": "01",
      "Février": "02",
      "Mars": "03",
      "Avril":"04",
      "Mai": "05",
      "Juin": "06",
      "Juillet": "07",
      "Août": "08",
      "Septembre": "09",
      "Octobre": "10",
      "Novembre": "11",
      "Décembre": "12"}

In [23]:
df_rename["MM"] = df_rename['Nom_Mois'].map(Month)

In [24]:
print(df_rename)

                                                 Date Qté 1000L Nom_Mois  \
4                                        Janvier 2020   2115961  Janvier
5                                        Février 2020   2008677  Février
6                                           Mars 2020   2164352     Mars
7                                          Avril 2020   2117406    Avril
8                                            Mai 2020   2109591      Mai
..                                                ...       ...      ...
64                                       Janvier 2025   1963404  Janvier
65                                       Février 2025   1819754  Février
66                                          Mars 2025   2064221     Mars
67                                                NaN       NaN      NaN
68  Source : Agreste - Enquête mensuelle laitière ...       NaN   Source

                                                Annee   MM
4                                                2020   01
5                                                2020   02
6                                                2020   03
7                                                2020   04
8                                                2020   05
..                                                ...  ...
64                                               2025   01
65                                               2025   02
66                                               2025   03
67                                                NaN  NaN
68  : Agreste - Enquête mensuelle laitière FranceA...  NaN

[65 rows x 5 columns]

In [25]:
df_rename["AAAAMM"]= df_rename["Annee"] + df_rename["MM"]

In [26]:
print(df_rename)

                                                 Date Qté 1000L Nom_Mois  \
4                                        Janvier 2020   2115961  Janvier
5                                        Février 2020   2008677  Février
6                                           Mars 2020   2164352     Mars
7                                          Avril 2020   2117406    Avril
8                                            Mai 2020   2109591      Mai
..                                                ...       ...      ...
64                                       Janvier 2025   1963404  Janvier
65                                       Février 2025   1819754  Février
66                                          Mars 2025   2064221     Mars
67                                                NaN       NaN      NaN
68  Source : Agreste - Enquête mensuelle laitière ...       NaN   Source

                                                Annee   MM  AAAAMM
4                                                2020   01  202001
5                                                2020   02  202002
6                                                2020   03  202003
7                                                2020   04  202004
8                                                2020   05  202005
..                                                ...  ...     ...
64                                               2025   01  202501
65                                               2025   02  202502
66                                               2025   03  202503
67                                                NaN  NaN     NaN
68  : Agreste - Enquête mensuelle laitière FranceA...  NaN     NaN

[65 rows x 6 columns]

In [28]:
Col1 = ["Date","Nom_Mois", "Annee", "MM"]

In [34]:
df_rename.drop(Col1, axis= 1, inplace=True)

In [35]:
print(df_rename)

   Qté 1000L  AAAAMM
4    2115961  202001
5    2008677  202002
6    2164352  202003
7    2117406  202004
8    2109591  202005
..       ...     ...
64   1963404  202501
65   1819754  202502
66   2064221  202503
67       NaN     NaN
68       NaN     NaN

[65 rows x 2 columns]

In [36]:
df_rename.to_csv("info_lait_final.csv")

In [37]:
df_m ="fichier_meteo_final.csv"
df_l = "info_lait_final.csv"

In [38]:
df_m.merge(df_m, df_l,left_on=None, right_on=None how='inner', on="AAAAMM")
pandas.merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=<no_default>, indicator=False, validate=None)[source]

TypeError: DataFrame.merge() got multiple values for argument 'how'